import type { Language } from "../context/LanguageContext";

const KANNADA_VALUES: Record<string, string> = {
  "Under Investigation": "ತನಿಖೆಯಲ್ಲಿದೆ",
  Registered: "ನೋಂದಾಯಿಸಲಾಗಿದೆ",
  "Charge Sheeted": "ಆರೋಪಪಟ್ಟಿ ಸಲ್ಲಿಸಲಾಗಿದೆ",
  "Charge-Sheeted": "ಆರೋಪಪಟ್ಟಿ ಸಲ್ಲಿಸಲಾಗಿದೆ",
  Closed: "ಮುಚ್ಚಲಾಗಿದೆ",
  "Closed (Task Completed)": "ಮುಚ್ಚಲಾಗಿದೆ (ಕಾರ್ಯ ಪೂರ್ಣಗೊಂಡಿದೆ)",
  "Closed - False Case": "ಮುಚ್ಚಲಾಗಿದೆ — ಸುಳ್ಳು ಪ್ರಕರಣ",
  "Disposed by Court": "ನ್ಯಾಯಾಲಯದಿಂದ ವಿಲೇವಾರಿ",
  Undetected: "ಪತ್ತೆಯಾಗಿಲ್ಲ",
  Pending: "ಬಾಕಿ",
  Filed: "ಸಲ್ಲಿಸಲಾಗಿದೆ",
  Submitted: "ಸಲ್ಲಿಸಲಾಗಿದೆ",
  "Pending Trial": "ವಿಚಾರಣೆ ಬಾಕಿ",
  Open: "ತೆರೆದಿದೆ",
  Active: "ಸಕ್ರಿಯ",
  Solved: "ಪರಿಹರಿಸಲಾಗಿದೆ",
  Acquitted: "ಖುಲಾಸೆಗೊಂಡಿದೆ",
  Convicted: "ದೋಷಿ ಎಂದು ತೀರ್ಮಾನಿಸಲಾಗಿದೆ",
  Heinous: "ಗಂಭೀರ",
  "Non-Heinous": "ಗಂಭೀರವಲ್ಲದ",
  Theft: "ಕಳ್ಳತನ",
  Assault: "ಹಲ್ಲೆ",
  "Attempt to Murder": "ಕೊಲೆ ಯತ್ನ",
  "Burglary/House-breaking": "ಕನ್ನಕಳವು / ಮನೆ ಒಡೆಯುವುದು",
  Cheating: "ವಂಚನೆ",
  Counterfeiting: "ನಕಲಿ ತಯಾರಿಕೆ",
  "Criminal Breach of Trust": "ಅಪರಾಧಿಕ ನಂಬಿಕೆ ದ್ರೋಹ",
  "Criminal Trespass": "ಅಪರಾಧಿಕ ಅತಿಕ್ರಮಣ",
  Cyberstalking: "ಸೈಬರ್ ಹಿಂಬಾಲಣೆ",
  Dacoity: "ಡಕಾಯಿತಿ",
  "Domestic Violence": "ಕೌಟುಂಬಿಕ ಹಿಂಸಾಚಾರ",
  "Dowry Harassment": "ವರದಕ್ಷಿಣೆ ಕಿರುಕುಳ",
  "Drug Trafficking": "ಮಾದಕ ವಸ್ತು ಸಾಗಣೆ",
  Forgery: "ನಕಲಿ ದಾಖಲೆ ಸೃಷ್ಟಿ",
  "Grievous Hurt": "ತೀವ್ರ ಗಾಯ",
  Hacking: "ಹ್ಯಾಕಿಂಗ್",
  "Hit and Run": "ಅಪಘಾತ ಮಾಡಿ ಪರಾರಿ",
  "Housebreaking by Night": "ರಾತ್ರಿ ಮನೆ ಒಡೆಯುವುದು",
  "Identity Theft": "ಗುರುತು ಕಳವು",
  "Illicit Liquor": "ಅಕ್ರಮ ಮದ್ಯ",
  Kidnapping: "ಅಪಹರಣ",
  Molestation: "ಲೈಂಗಿಕ ಕಿರುಕುಳ",
  Murder: "ಕೊಲೆ",
  "Online Financial Fraud": "ಆನ್‌ಲೈನ್ ಹಣಕಾಸು ವಂಚನೆ",
  "Possession of Narcotics": "ಮಾದಕ ವಸ್ತು ಹೊಂದಿರುವುದು",
  "Public Nuisance": "ಸಾರ್ವಜನಿಕ ಉಪದ್ರವ",
  Rape: "ಅತ್ಯಾಚಾರ",
  "Rash Driving": "ಅಜಾಗರೂಕ ಚಾಲನೆ",
  Rioting: "ಗಲಭೆ",
  Robbery: "ದರೋಡೆ",
  Stalking: "ಹಿಂಬಾಲಣೆ",
  "Unlawful Assembly": "ಕಾನೂನುಬಾಹಿರ ಸಭೆ",
  "Vehicle Theft": "ವಾಹನ ಕಳವು",
  "Cyber Crime": "ಸೈಬರ್ ಅಪರಾಧ",
  "Offences Against Body": "ದೇಹದ ವಿರುದ್ಧದ ಅಪರಾಧಗಳು",
  "Motor Vehicle Accident": "ಮೋಟಾರು ವಾಹನ ಅಪಘಾತ",
  Narcotics: "ಮಾದಕ ವಸ್ತುಗಳು",
  Case: "ಪ್ರಕರಣ",
  FIR: "ಎಫ್‌ಐಆರ್",
  "Police Station": "ಪೊಲೀಸ್ ಠಾಣೆ",
  "Traffic Police Station": "ಸಂಚಾರ ಪೊಲೀಸ್ ಠಾಣೆ",
  "Investigating Officer (IO)": "ತನಿಖಾಧಿಕಾರಿ",
  Constable: "ಕಾನ್ಸ್‌ಟೇಬಲ್",
  Inspector: "ಇನ್ಸ್‌ಪೆಕ್ಟರ್",
  "Sub-Inspector": "ಉಪ ನಿರೀಕ್ಷಕ",
  "Police Sub-Inspector": "ಪೊಲೀಸ್ ಉಪ ನಿರೀಕ್ಷಕ",
  Superintendent: "ಪೊಲೀಸ್ ಅಧೀಕ್ಷಕರು",
  SP: "ಪೊಲೀಸ್ ಅಧೀಕ್ಷಕರು",
  Unknown: "ತಿಳಿದಿಲ್ಲ",
  "Not recorded": "ದಾಖಲಾಗಿಲ್ಲ",
  "Unassigned station": "ನಿಯೋಜಿಸದ ಠಾಣೆ",
  State: "ರಾಜ್ಯ",
};

export const displayKnownValue = (value: string, language: Language) => {
  if (language !== "kn" || !value) return value;
  return KANNADA_VALUES[value.trim()] || value;
};
